### ISSUE TITLE
3D View does not appear in Fedora 36

### ISSUE THREAD

**Issue by dsancheznet** [multigcs/viaconstructor#1]
Apparently the Wayland integraton does not work.

Best regards
DSanchez

**Comment by dsancheznet** [comment]
Just FYI,
the bug continues on Fedora 38.

Best Regards
DSanchez

**Comment by multigcs** [comment]
I think that Wayland only supports OpenGL-ES

Maybe you can try to install XWayland:
https://unix.stackexchange.com/questions/511134/why-wayland-is-using-opengl-es-instead-of-opengl

**Comment by dsancheznet** [comment]
I'm not really able to do that without breaking my actual desktop, and that's a pitty. Maybe there is an alternative solution, considering that Red Hat has started marking xorg as deprecated. In the long run, some workaround will probably be neccessary. 

Best regards
DSanchez

**Comment by dsancheznet** [comment]
On a default Fedora 40 installation, the 3D view works correctly now. 
Thanks for all.

Best regards and keep the good work up.

**Comment by dsancheznet** [comment]
I just updated to Fedora 41 and it has the same problem again! 

I'd like to find out what the problem exactly is. If it is a certain library, I'd take the time to see if I can downgrade that library.

Best regards

**Comment by multigcs** [comment]
there is a OpenGL-Info at startup like:

OpenGL-Version: 4.6 (Compatibility Profile) Mesa 22.3.6

what does it say for you

**Comment by dsancheznet** [comment]
Sorry for the delay.

The console prints out the following ( I'll include an error here that could be relevant ):

```
QSocketNotifier: Can only be used with threads started with QThread
OpenGL-Version: 4.6 (Compatibility Profile) Mesa 24.2.8
```
