### ISSUE TITLE
Windows zip file unusable link

### ISSUE THREAD

**Issue by notalfredo** [multigcs/viaconstructor#14]
Hello in the readme for windows support you mention you can get it up and running using `zip` file using the link https://www.multixmedia.org/viaconstructor.zip but when you click on the link it ask for a username and password not sure if its intentional or not could not find anything regarding a username and password in the README.

<img width="844" alt="image" src="https://github.com/user-attachments/assets/07afcb43-aa7a-4742-a2ae-322f4ebdf6e1">

Thanks

**Comment by multigcs** [comment]
fixed, thanks
