### ISSUE TITLE
Freeze when Step==0

### ISSUE THREAD

**Issue by speters** [multigcs/viaconstructor#2]
Thanks for this cool piece of software! (I accidentally stumbled over this by following a Google Search Link to Finger's Forum.)
Installation was flawless via pip on Arch Linux.

While playing with it, I realized that setting _Step:=0_ freezes the program. Maybe do a sanity-check for very small values, too.

PS:
I realized another small UI bug:
Entering numbers after the decimal separator is a bit strange, as it requires to delete a decimal place prior to entering.

**Comment by multigcs** [comment]
Thank you
I have released the latest source (v0.4.7) i think this bug is fixed there.

PS: i know the problem but can not fix it, depends on qt5

**Comment by multigcs** [comment]
if it not works, please reopen this bug
