### ISSUE TITLE
get error when open file

### ISSUE THREAD

**Issue by sofwarestore** [multigcs/viaconstructor#6]
hello
i want to open my file but i get error like this:

ERROR: parsing machine_cmd: list index out of range
error while drawing machine commands
ERROR: parsing machine_cmd: list index out of range
error while drawing machine commands

it this normal 
![Screenshot (10)](https://github.com/multigcs/viaconstructor/assets/76522198/6bd2148d-0e48-4c53-a4c5-d289321efbc5)

**Comment by multigcs** [comment]
it's not normal, but without your file, i can not check the real problem :(
you can try to delete some parts of your file to locate the critical parts.

**Comment by sofwarestore** [comment]
here my file. can you help check it
[1.zip](https://github.com/multigcs/viaconstructor/files/14109769/1.zip)

**Comment by multigcs** [comment]
![1](https://github.com/multigcs/viaconstructor/assets/4227622/62771a1a-3009-4c14-98ef-eeca65738130)

hmm, i think i need you configuration too, because i can load it with my setup (viaconstructor.json)

**Comment by sofwarestore** [comment]
yes it can load..Does this error not affect the results of the generated gcode?

**Comment by multigcs** [comment]
viaconstructor /tmp/1.dxf 
loading file: 100.0%
dxfread: selected layers: Layer 1
combining segments: 100.0%
set offsets: 100.0%
OpenGL-Version: 3.0 Mesa 20.3.5
calc offset path: 100.0%
generating machine commands: 100.0%

**Comment by multigcs** [comment]
i have no errors seen in my outputs.

you can check the gcode with a an simulator

**Comment by sofwarestore** [comment]
okay,,,thank you, it make me feel not worry 
on my dxf there are 10 part 

is there a way to set it so that gcode completes 1 part first, then the other part

I have tried changing several settings but have not found suitable results, it still cut all the all inside parts first and then the outside

**Comment by multigcs** [comment]
or check the red lines in the 3d preview , this is the parsed gcode output

**Comment by multigcs** [comment]
>> is there a way to set it so that gcode completes 1 part first, then the other part
no, not yet, sorry, but you can open a feature request, so i don't forget it. at this moment i have not so much time to implement it

**Comment by sofwarestore** [comment]
Ok thanks you..

**Comment by sofwarestore** [comment]
Okay thanks you

**Comment by multigcs** [comment]
@sofwarestore : i have added new option: Global->Mill->Object-Oder: 'per_object'
is merged to main, but not yet in pypi (pip)
