### ISSUE TITLE
Is there a way to follow a path that is not a closed polygon?

### ISSUE THREAD

**Issue by faern** [multigcs/viaconstructor#9]
I have the path as shown in the first attached picture. This will cut out two parts from a piece of wood. I do not want to cut along the outside of the wood stock that I have, because that's where I clamp it down in my mill, and also, the outside edges are already fine. I just need to mill the inside edges/cut the parts away from the stock.

![screenshot_2024-04-01_22-49-33](https://github.com/multigcs/viaconstructor/assets/332294/294f9ec8-1e64-4b2a-87a8-4e3851a17312)

When I import it into viaConstructor I get these two results, depending on how I draw the line:

![screenshot_2024-04-01_22-50-19](https://github.com/multigcs/viaconstructor/assets/332294/ae2d5cb1-b8f2-4bb1-96a7-8f1724a83da6)

1. The path is one continuous line in the svg, but it overlaps itself to backtrack over where it has already been. This is actually how I want the mill to move - But the path becomes closed in viaConstructor and it will mill along a non-existing line from the last point in the line back to the first. Can this be disabled? I want it to either run the same path backwards for the next layer, or go back to the start position at the safe Z height to start over for the next layer.

![screenshot_2024-04-01_22-51-08](https://github.com/multigcs/viaconstructor/assets/332294/2ae399cb-3a1d-488d-834e-fba4ad70ecf1)

2. The path branch out in some places, so it's not one continuous segment - It will treat the line as two separate objects and mill them individually. The result is kind of what I want. But I'd like it to finish a single layer before stepping down further in Z. Is this possible? Can I tell it to mill layer one of **all objects** before starting with layer two?

What I'm looking for is usually called something like "trace" or "follow path" in some other CAM software.

**Comment by faern** [comment]
Currently the best solution I have come up with is to add a dummy "return path" to my svg file, outside the entire cutting area[1] that viaConstructor can use to return to the start. And then manually edit the resulting gcode to set `Z` to my safe travel height during all those moves.

[1] If the return path cross any existing path, it generates really weird gcode for me.

**Comment by multigcs** [comment]
Can you upload your drawing file? I cannot reproduce the problem.

**Comment by faern** [comment]
Sure! Here are my two svg files. They are not identical to the ones in the screenshots, because I continued working on them. But they showcase the exact same behaviors. They are created by making a sketch in FreeCAD and exporting as flattened SVG.

![viaconstructor-test-multiple-objects](https://github.com/multigcs/viaconstructor/assets/332294/a3a8575d-fc3e-47df-8eeb-cf5d7f23fec1)
![viaconstructor-test-unwanted-closed-loop](https://github.com/multigcs/viaconstructor/assets/332294/02196881-8a8d-4a92-b889-f9c8ca9dc046)

**Comment by faern** [comment]
Hmm. Wait. Seems like I only get this weird behavior when selecting `svgread` on file open. I did that without thinking since what I am opening is an SVG file. If I select `dxfread` I think it behaves as I want it to. Need further investigation, but looks promising. I assumed `dxfread` was for DXF files and it was a "bug" that it even asked this when selecting an SVG.

I see now that if I try to open a dxf file it throws up a completely different dialogue altogether

**Comment by multigcs** [comment]
thanks, svgread is a litle bit buggy :(

dxfread using the converter from inkscape (/usr/share/inkscape/extensions/dxf_outlines.py),
this works better than the svgpathtools used by the svgread plugin

**Comment by faern** [comment]
I see. So `dxfread` first converts it to dxf and then operates on that? Then maybe it's preferable/simpler if I just export as DXF from FreeCAD directly? I just made a habit out of working with svg.

**Comment by faern** [comment]
The results now look just like I want them I think! Thank you very much for the help, and for creating this awesome tool! Was looking a while for a good 2.5D CAM tool for Linux.
